---
version: 2.1

executors:
  executor:
    docker:
      - image: cimg/openjdk:8.0
    working_directory: ~/repo

jobs:
  build:
    parameters:
      upload:
        default: false
        description: "Upload to Artefact Repository"
        type: boolean
    executor: executor
    steps:
      - checkout
      - restore_cache:
          key: nexus-casc-plugin-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: nexus-casc-plugin-{{ checksum "pom.xml" }}
      - run: mvn package
      - when:
          condition: << parameters.upload >>
          steps:
            - run:
                name: Install jFrog CLI
                command: curl -fL https://getcli.jfrog.io | sh
            - run:
                name: Push to Artifactory
                environment:
                  JFROG_CLI_OFFER_CONFIG: "false"
                command: |
                  export JFROG_CLI_BUILD_NAME="$CIRCLE_PROJECT_REPONAME"
                  export JFROG_CLI_BUILD_NUMBER="$CIRCLE_BUILD_NUM"
                  export JFROG_CLI_BUILD_URL="$CIRCLE_BUILD_URL"
                  ./jfrog rt config --url="$ARTIFACTORY_URL" --user="$ARTIFACTORY_USER" --apikey="$ARTIFACTORY_APIKEY" --interactive=false adaptive
                  ./jfrog rt build-add-git --server-id=adaptive
                  ./jfrog rt build-collect-env
                  ./jfrog rt mvn-config --server-id-deploy=adaptive --repo-deploy-releases="$ARTIFACTORY_REPO" --repo-deploy-snapshots="$ARTIFACTORY_REPO"
                  M2_HOME=/opt/apache-maven ./jfrog rt mvn install -DskipITs -DskipTests
                  ./jfrog rt build-publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v.*/
  release:
    jobs:
      - build:
          upload: true
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
